- hosts:  localhost
  tasks:
  -  name: "Going to launch 3 EC2 Iinstance on  AWS"
    ec2_instance:
            region:  ap-south-1
            image_id:  ami-08f63db601b82ff5f
            instance_type:  t2.micro
            vpc_subnet_id:  subnet-07bb3f8a665cc31ec
            security_group: sg-46ea9624
            key_name:  mykey
            tags:
                    Name:  "{{ item }}"
            state:  present
            aws_access_key:  {{ access_key }}
            aws_secret_key:  {{ secret_key }}

    loop:

          - MasterNode
          - SlaveNodes
          - SlaveNodes
