apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: vishsqlpod
  name: vishsqlpod
spec:
  replicas: 2
  selector:
    matchLabels:
      run: vishsqlpod

  template:
    metadata:
      labels:
        run:  vishsqlpod

    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                      name:  vishsecret
                      key:   pass
        - name: MYSQL_DATABASE
          value: vishdb
        - name: MYSQL_USER
          value: vishal
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                      name:  vishsecret
                      key:   pass
        image: mysql:5.7
        name: vishsqlpod
